### ISSUE TITLE
Error in training on timelapses

### ISSUE THREAD

**Issue by KartikeyKansal1** [AllenCellModeling/cyto-dl#406]
Hello, I'm trying to train on timelapses but the dataloader considers the time dimension as Z

I ran the following code and got the output below:
```
from aicsimageio import AICSImage

# Load the image using AICSImage
image_path = 'data/labelfree/training_data/Tension1.tif'
img = AICSImage(image_path)

# Print the shape of the image
print("Image shape:", img.shape)

# Print the number of dimensions
print("Image dimensions:", img.dims)

# Print the dimension order
print("Dimension order:", img.dims.order)
```

```
Image shape: (1, 1, 20, 512, 512)
Image dimensions: <Dimensions [T: 1, C: 1, Z: 20, Y: 512, X: 512]>
Dimension order: TCZYX
```
while the actual dimensions of the image are different: 
<img width="512" alt="image" src="https://github.com/AllenCellModeling/cyto-dl/assets/56447914/a9bc1f4d-15ba-488e-9f53-8e4fb12a676e">

I still wanna use 2D convolutions so I can't work with Z. Any suggestions?

I tried with conv3d and pulling out Z slices but that doesn't seem to work either.

**Comment by benjijamorris** [comment]
Hi @KartikeyKansal1! I haven't tried this exact thing, but my first thought is to incorporate the [splitdim transform](https://docs.monai.io/en/stable/transforms.html#splitdimd)https://docs.monai.io/en/stable/transforms.html#splitdimd)

in something like:
```
transforms:
# loading image as Z(really T)YX
# split z dimension
_target_: monai.transforms.SplitDimd
keys: ${source_col}
dim: 1 # this is your Z/T dimension
list_output: True # this returns a list of dictionaries with the same keys as your original one
```
I think this will work, but your batches will be 20*batch_size and contain all the timepoints from a single image (so not i.i.d).

Another approach would be to use the  [aicsimageloader class](https://allencellmodeling.github.io/cyto-dl/cyto_dl.image.io.aicsimage_loader.html#cyto_dl.image.io.aicsimage_loader.AICSImageLoaderd). For this, you would create a csv with one row per timepoint like this:
| path | T | C |
|---|-|-|
|/path1.tif | 0 | 0}
|/path1.tif| 1 | 0 |
|...|...|...|
|/path2.tif | 0 | 0 |
|/path2.tif | 1 | 0|
IO here might be slower, but you'll get better random sampling and have finer control over the batch size. 

Let me know if either of these approaches works for you or if you want more details!

**Comment by KartikeyKansal1** [comment]
Hi @benjijamorris , thank you for the suggestions. I think I would like to go with the second approach here. 

I'm assuming my data config file should look something like this
```
train:
    _target_: monai.transforms.Compose
    transforms:
      - _target_: monai.transforms.LoadImaged
        keys: ${target_col}
        reader:
          - _target_: cyto_dl.image.io.aicsimage_loader.AICSImageLoaderd
            dimension_order_out: YX
            C: 0
            Z: 0
```
I'm  confused on how to create this csv, how will I pair the source and target column.

**Comment by benjijamorris** [comment]
Good question! This approach would replace the LoadImaged Transform, so
```
train:
    _target_: monai.transforms.Compose
    transforms:
        - _target_: cyto_dl.image.io.aicsimage_loader.AICSImageLoaderd
          path_key: seg_path # key in your csv with the path to your segmentation
          out_key: seg # name to load your segmentation into

        - _target_: cyto_dl.image.io.aicsimage_loader.AICSImageLoaderd
          path_key: raw_path # key in your csv with the path to your paired raw image (i.e. in the same row in your csv)
          out_key: raw # name to load your raw image into
```
This will give you a dictionary like 
```
{'raw': np.array(), 'seg': np.array(), ... }
```

**Comment by KartikeyKansal1** [comment]
Gotcha, 

Will rest of the transforms can still be applied to ${data.columns}? and I can define columns as
```
columns:
  - ${seg_col}
  - ${raw_col}
  - ${T_col}
  - ${C_col}
  - ${dim_col}
```
And spatial_dims=3 since ZYX?

**Comment by benjijamorris** [comment]
I would change `${data.columns}` to a yaml list like
```
- ${seg_col}
- ${raw_col}
```
spatial dims should be 2 since your model inputs will be CYX

**Comment by KartikeyKansal1** [comment]
Getting this error:

```
Error executing job with overrides: ['experiment=im2im/labelfree.yaml', 'trainer=cpu', 'spatial_dims=2']
Traceback (most recent call last):
  File "/Users/kartikeykansal/miniconda3/envs/cytodl_env_240711_v2/lib/python3.10/site-packages/monai/transforms/transform.py", line 141, in apply_transform
    return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
  File "/Users/kartikeykansal/miniconda3/envs/cytodl_env_240711_v2/lib/python3.10/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
    return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
  File "/Users/kartikeykansal/miniconda3/envs/cytodl_env_240711_v2/lib/python3.10/site-packages/monai/transforms/spatial/dictionary.py", line 1991, in __call__
    d[key] = self.zoomer(
  File "/Users/kartikeykansal/miniconda3/envs/cytodl_env_240711_v2/lib/python3.10/site-packages/monai/transforms/spatial/array.py", line 1092, in __call__
    _zoom = ensure_tuple_rep(self.zoom, img.ndim - 1)  # match the spatial image dim
AttributeError: 'str' object has no attribute 'ndim'

```

I'm also not sure why the dimension_order_out is ZYX in the table.

**Comment by benjijamorris** [comment]
Looks like the `zoom` transform is operating on a path instead of the loaded image. I'd make sure that whatever you choose as the `out_key` is the key that's being augmented in later transforms. 

Good point, that should be CYX

**Comment by KartikeyKansal1** [comment]
I removed the zoom transform

Error I'm getting now:
```
File "/Users/kartikeykansal/miniconda3/envs/cytodl_env_240711_v2/lib/python3.10/site-packages/monai/utils/type_conversion.py", line 332, in convert_data_type
    raise ValueError(f"Unsupported output type: {output_type}")
ValueError: Unsupported output type: <class 'str'>
```

My data config file:
```
_target_: cyto_dl.datamodules.dataframe.DataframeDatamodule

path: 
cache_dir:

num_workers: 0
batch_size: 1
pin_memory: True
split_column: 
columns:
  - ${raw_col}
  - ${signal_col}

transforms:
  train:
    _target_: monai.transforms.Compose
    transforms:
      - _target_: cyto_dl.image.io.aicsimage_loader.AICSImageLoaderd
        path_key: raw_path # key in your csv with the path to your paired raw image (i.e. in the same row in your csv)
        out_key: raw # name to load your raw image into

      - _target_: cyto_dl.image.io.aicsimage_loader.AICSImageLoaderd
        path_key: signal_path # key in your csv with the path to your paired signal image (i.e. in the same row in your csv)
        out_key: signal # name to load your signal image into

      - _target_: monai.transforms.ToTensord
        keys: 
          - ${raw_col}
          - ${signal_col}
      - _target_: monai.transforms.NormalizeIntensityd
        keys: 
          - ${raw_col}
          - ${signal_col}
        channel_wise: True
      - _target_: cyto_dl.image.transforms.RandomMultiScaleCropd
        keys: 
          - ${raw_col}
          - ${signal_col}
        patch_shape: ${data._aux.patch_shape}
        patch_per_image: 1
        scales_dict: ${kv_to_dict:${data._aux._scales_dict}}

  test:
    _target_: monai.transforms.Compose
    transforms:
      - _target_: cyto_dl.image.io.aicsimage_loader.AICSImageLoaderd
        path_key: raw_path # key in your csv with the path to your paired raw image (i.e. in the same row in your csv)
        out_key: raw # name to load your raw image into

      - _target_: cyto_dl.image.io.aicsimage_loader.AICSImageLoaderd
        path_key: signal_path # key in your csv with the path to your paired signal image (i.e. in the same row in your csv)
        out_key: signal # name to load your signal image into

      - _target_: monai.transforms.ToTensord
        keys: 
          - ${raw_col}
          - ${signal_col}
      - _target_: monai.transforms.NormalizeIntensityd
        keys: 
          - ${raw_col}
          - ${signal_col}

  predict:
    _target_: monai.transforms.Compose
    transforms:
      - _target_: cyto_dl.image.io.aicsimage_loader.AICSImageLoaderd
        path_key: raw_path # key in your csv with the path to your paired raw image (i.e. in the same row in your csv)
        out_key: raw # name to load your raw image into

      - _target_: monai.transforms.ToTensord
        keys: ${raw_col}
      - _target_: monai.transforms.NormalizeIntensityd
        keys: ${raw_col}
        channel_wise: True

  valid:
    _target_: monai.transforms.Compose
    transforms:
      - _target_: cyto_dl.image.io.aicsimage_loader.AICSImageLoaderd
        path_key: raw_path # key in your csv with the path to your paired raw image (i.e. in the same row in your csv)
        out_key: raw # name to load your raw image into

      - _target_: cyto_dl.image.io.aicsimage_loader.AICSImageLoaderd
        path_key: signal_path # key in your csv with the path to your paired signal image (i.e. in the same row in your csv)
        out_key: signal # name to load your signal image into

      - _target_: monai.transforms.ToTensord
        keys: 
          - ${raw_col}
          - ${signal_col}
      - _target_: monai.transforms.NormalizeIntensityd
        keys: 
          - ${raw_col}
          - ${signal_col}
        channel_wise: True
      - _target_: cyto_dl.image.transforms.RandomMultiScaleCropd
        keys: 
          - ${raw_col}
          - ${signal_col}
        patch_shape: ${data._aux.patch_shape}
        patch_per_image: 1
        scales_dict: ${kv_to_dict:${data._aux._scales_dict}}

_aux:
  _scales_dict:
    - - ${raw_col}
      - [1]
    - - ${signal_col}
      - [1]

```
